//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace web_app.web_db_service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_movie_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_serial_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_user_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_golden_glob_winnersOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_oscars_winnerOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_serial_avg_rateOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_fim_serial_rateOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_actors_film_serialsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::web_app.Properties.Settings.Default.web_app_web_db_service_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_movie_listCompletedEventHandler get_movie_listCompleted;
        
        /// <remarks/>
        public event get_serial_listCompletedEventHandler get_serial_listCompleted;
        
        /// <remarks/>
        public event get_user_listCompletedEventHandler get_user_listCompleted;
        
        /// <remarks/>
        public event get_golden_glob_winnersCompletedEventHandler get_golden_glob_winnersCompleted;
        
        /// <remarks/>
        public event get_oscars_winnerCompletedEventHandler get_oscars_winnerCompleted;
        
        /// <remarks/>
        public event get_serial_avg_rateCompletedEventHandler get_serial_avg_rateCompleted;
        
        /// <remarks/>
        public event get_fim_serial_rateCompletedEventHandler get_fim_serial_rateCompleted;
        
        /// <remarks/>
        public event get_actors_film_serialsCompletedEventHandler get_actors_film_serialsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_movie_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_movie_list() {
            object[] results = this.Invoke("get_movie_list", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_movie_listAsync() {
            this.get_movie_listAsync(null);
        }
        
        /// <remarks/>
        public void get_movie_listAsync(object userState) {
            if ((this.get_movie_listOperationCompleted == null)) {
                this.get_movie_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_movie_listOperationCompleted);
            }
            this.InvokeAsync("get_movie_list", new object[0], this.get_movie_listOperationCompleted, userState);
        }
        
        private void Onget_movie_listOperationCompleted(object arg) {
            if ((this.get_movie_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_movie_listCompleted(this, new get_movie_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_serial_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_serial_list() {
            object[] results = this.Invoke("get_serial_list", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_serial_listAsync() {
            this.get_serial_listAsync(null);
        }
        
        /// <remarks/>
        public void get_serial_listAsync(object userState) {
            if ((this.get_serial_listOperationCompleted == null)) {
                this.get_serial_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_serial_listOperationCompleted);
            }
            this.InvokeAsync("get_serial_list", new object[0], this.get_serial_listOperationCompleted, userState);
        }
        
        private void Onget_serial_listOperationCompleted(object arg) {
            if ((this.get_serial_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_serial_listCompleted(this, new get_serial_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_user_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_user_list() {
            object[] results = this.Invoke("get_user_list", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_user_listAsync() {
            this.get_user_listAsync(null);
        }
        
        /// <remarks/>
        public void get_user_listAsync(object userState) {
            if ((this.get_user_listOperationCompleted == null)) {
                this.get_user_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_user_listOperationCompleted);
            }
            this.InvokeAsync("get_user_list", new object[0], this.get_user_listOperationCompleted, userState);
        }
        
        private void Onget_user_listOperationCompleted(object arg) {
            if ((this.get_user_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_user_listCompleted(this, new get_user_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_golden_glob_winners", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_golden_glob_winners(int year) {
            object[] results = this.Invoke("get_golden_glob_winners", new object[] {
                        year});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_golden_glob_winnersAsync(int year) {
            this.get_golden_glob_winnersAsync(year, null);
        }
        
        /// <remarks/>
        public void get_golden_glob_winnersAsync(int year, object userState) {
            if ((this.get_golden_glob_winnersOperationCompleted == null)) {
                this.get_golden_glob_winnersOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_golden_glob_winnersOperationCompleted);
            }
            this.InvokeAsync("get_golden_glob_winners", new object[] {
                        year}, this.get_golden_glob_winnersOperationCompleted, userState);
        }
        
        private void Onget_golden_glob_winnersOperationCompleted(object arg) {
            if ((this.get_golden_glob_winnersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_golden_glob_winnersCompleted(this, new get_golden_glob_winnersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_oscars_winner", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_oscars_winner(int year) {
            object[] results = this.Invoke("get_oscars_winner", new object[] {
                        year});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_oscars_winnerAsync(int year) {
            this.get_oscars_winnerAsync(year, null);
        }
        
        /// <remarks/>
        public void get_oscars_winnerAsync(int year, object userState) {
            if ((this.get_oscars_winnerOperationCompleted == null)) {
                this.get_oscars_winnerOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_oscars_winnerOperationCompleted);
            }
            this.InvokeAsync("get_oscars_winner", new object[] {
                        year}, this.get_oscars_winnerOperationCompleted, userState);
        }
        
        private void Onget_oscars_winnerOperationCompleted(object arg) {
            if ((this.get_oscars_winnerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_oscars_winnerCompleted(this, new get_oscars_winnerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_serial_avg_rate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_serial_avg_rate() {
            object[] results = this.Invoke("get_serial_avg_rate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_serial_avg_rateAsync() {
            this.get_serial_avg_rateAsync(null);
        }
        
        /// <remarks/>
        public void get_serial_avg_rateAsync(object userState) {
            if ((this.get_serial_avg_rateOperationCompleted == null)) {
                this.get_serial_avg_rateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_serial_avg_rateOperationCompleted);
            }
            this.InvokeAsync("get_serial_avg_rate", new object[0], this.get_serial_avg_rateOperationCompleted, userState);
        }
        
        private void Onget_serial_avg_rateOperationCompleted(object arg) {
            if ((this.get_serial_avg_rateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_serial_avg_rateCompleted(this, new get_serial_avg_rateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_fim_serial_rate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_fim_serial_rate() {
            object[] results = this.Invoke("get_fim_serial_rate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_fim_serial_rateAsync() {
            this.get_fim_serial_rateAsync(null);
        }
        
        /// <remarks/>
        public void get_fim_serial_rateAsync(object userState) {
            if ((this.get_fim_serial_rateOperationCompleted == null)) {
                this.get_fim_serial_rateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_fim_serial_rateOperationCompleted);
            }
            this.InvokeAsync("get_fim_serial_rate", new object[0], this.get_fim_serial_rateOperationCompleted, userState);
        }
        
        private void Onget_fim_serial_rateOperationCompleted(object arg) {
            if ((this.get_fim_serial_rateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_fim_serial_rateCompleted(this, new get_fim_serial_rateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_actors_film_serials", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_actors_film_serials(string name, string familyName) {
            object[] results = this.Invoke("get_actors_film_serials", new object[] {
                        name,
                        familyName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_actors_film_serialsAsync(string name, string familyName) {
            this.get_actors_film_serialsAsync(name, familyName, null);
        }
        
        /// <remarks/>
        public void get_actors_film_serialsAsync(string name, string familyName, object userState) {
            if ((this.get_actors_film_serialsOperationCompleted == null)) {
                this.get_actors_film_serialsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_actors_film_serialsOperationCompleted);
            }
            this.InvokeAsync("get_actors_film_serials", new object[] {
                        name,
                        familyName}, this.get_actors_film_serialsOperationCompleted, userState);
        }
        
        private void Onget_actors_film_serialsOperationCompleted(object arg) {
            if ((this.get_actors_film_serialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_actors_film_serialsCompleted(this, new get_actors_film_serialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void get_movie_listCompletedEventHandler(object sender, get_movie_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_movie_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_movie_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void get_serial_listCompletedEventHandler(object sender, get_serial_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_serial_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_serial_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void get_user_listCompletedEventHandler(object sender, get_user_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_user_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_user_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void get_golden_glob_winnersCompletedEventHandler(object sender, get_golden_glob_winnersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_golden_glob_winnersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_golden_glob_winnersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void get_oscars_winnerCompletedEventHandler(object sender, get_oscars_winnerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_oscars_winnerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_oscars_winnerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void get_serial_avg_rateCompletedEventHandler(object sender, get_serial_avg_rateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_serial_avg_rateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_serial_avg_rateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void get_fim_serial_rateCompletedEventHandler(object sender, get_fim_serial_rateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_fim_serial_rateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_fim_serial_rateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void get_actors_film_serialsCompletedEventHandler(object sender, get_actors_film_serialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_actors_film_serialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_actors_film_serialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591